<?php

function lang($ph)
{
    static $lang = array(
        'titleLog' => 'login',
        'reg' => 'register',
        'cat' => 'Categories',
        'sc' => 'search',
        'all' => 'All Categories',
        'home' => 'home',
        'cash' => 'Cash On Delivery',
        'best' => 'Best Seller',
        'el'=> 'Electronics',
        'cus'=>'Customer Review',
        '5'=> '5.0',
        '4' =>'4.0',
        '3'=>'3.5',
        '3.0' =>'3.0',
        '2' =>'2.5',
        'user' => 'Username',
        'pass' => 'Password',
        'rem' => 'Remember me?',
        'dn'=> 'Don\'t have an account?',
        'regn'=> 'Register Now',
        'name'=> 'full name',
        'em' => 'email',
        'repass' => 'Confirm Password',
        'accept' => 'I Accept to the Terms & Conditions',
        'phone' => 'phone',
        'this1' => 'this email alredy exist',
        'this2' => 'this phone alredy exist',
        'this3'=> 'this username alredy exist',
        'msg' => 'you will be redirect in 3 seconds',
        'or'=> 'or',
        'ver' => 'verification code',
        'msgver' => 'your verification code invalid',
        'account' => 'account settings',
        'log' => 'logout',
        'change'=> 'change photo',
        'about' => 'About',
        'pur'=> 'Purchases',
        'details' => 'View Details',
        'quik'=> 'Quick View',
        'delete'=> 'delete account',
        'edit' => 'Edit Profile',
        'update'=> 'update',
        'forgot'=> 'Forgot password?',
        'view' => 'view more',
        'type' => 'type',
        'text'=> 'If you\'re considering a new laptop, looking for a powerful new car stereo or shopping for a new HDTV, we make it easy to
        find exactly what you need at a price you can afford. We offer Every Day Low Prices on TVs, laptops, cell phones, tablets
        and iPads, video games, desktop computers, cameras and camcorders, audio, video and more.',
        'free'=> 'Free Shipping',
        'desfree'=>'on orders over $100',
        'fast'=> 'Fast Delivery',
        'desfast'=> 'World Wide',
        'big' =>'Big Choice',
        'desbig'=> 'of Products',
        'qklink' => 'Quick Links',
        'aboutt'=> 'About Us',
        'contact' => 'Contact Us',
        'help' => 'Help',
        'fa'=> 'Faqs',
        'term' => 'Terms of use',
        'priv' => 'Privacy Policy',
        'get' => 'Get in Touch',
        'news' => 'Newsletter',
        'desnews'=>'Free Delivery on your first order!',
        'follow'=> 'Follow Us on',
        'payment'=>'Payment Method',
        'cash'=>'cash on delevery',
        'pr'=>'price',
        'check'=>'Checkout',
        'add'=> 'Add a new Details',
        'chst'=>'choose statu',
        'nw'=>'new',
        'lknw'=> 'Like new',
        'us'=>'used',
        'vr'=>"very old",
        'productnm'=>'Product Name',
        'qn'=>'Quantity',
        'product'=> 'Product',
        'mobile'=>'mobile number',
        'adress'=>'Full adress',
        'del'=> 'Delivery to this Address',
        'selpm'=> 'select payment method',
        'pm'=> 'payment',
        'post'=> 'Postal account',
        'ppl'=>'PayPal Account',
        'select'=> 'select',
        'info'=> 'information',
        'inv'=> 'print invoice',
        'plsinv'=> 'Please pay for this instrument and send the clip by clicking the button below',
        'send'=> 'send',
        'comup'=> 'update comment',
        'dt'=>'date',
        'top' => ' Top Deals & Discounts ',
        'can'=> 'cancel',
        'chimg'=>'choose image',
        'upload'=> 'upload',
        'en'=> 'english',
        'ar'=> 'arabic',
        'fr'=> 'french',
        'shop'=> 'shop now',
        'srhe'=> 'Search Here..',
        'prnm'=> 'Product name...',
        'contactus'=> 'contact us',
        'call'=> 'call us',
        'ms'=> 'message',
        'welcome'=> 'welcome'


    );

    return $lang[$ph];

}

?>