<?php

function lang($ph)
{
    static $lang = array(
        'titleLog' => 's\'identifier',
        'reg' => 'S\'inscrire',
        'cat' => 'Les catégories',
        'sc' => 'chercher',
        'all' => 'toutes catégories',
        'home' => 'Principale',
        'cash' => 'Paiement à la livraison',
        'best' => 'Best-seller',
        'el'=> 'électronique',
        'cus'=>'Avis client',
        '5'=> '5.0',
        '4' =>'4.0',
        '3'=>'3.5',
        '3.0' =>'3.0',
        '2' =>'2.5',
        'user' => 'Nom d\'utilisateur',
        'pass' => 'Mot de passe',
        'rem' => 'Souviens-toi de moi?',
        'dn'=> 'Vous n\'avez pas de compte?',
        'regn'=> 'S\'inscrire maintenant',
        'name'=> 'nom complet',
        'em' => 'email',
        'repass' => 'Confirmez le mot de passe',
        'accept' => 'J\'accepte les termes et conditions',
        'phone' => 'téléphone',
        'this1' => 'cet email existe déjà',
        'this2' => 'ce téléphone existe déjà',
        'this3'=> 'Ce nom d\'utilisateur existe déjà',
        'msg' => 'vous serez redirigé dans 3 secondes',
        'or'=> 'ou',
        'ver' => 'code de vérification',
        'msgver' => 'votre code de vérification n\'est pas valide',
        'account' => 'paramètres du compte',
        'log' => 'Se déconnecter',
        'change'=> 'changer la photo',
        'about' => 'À propos de',
        'pur'=> 'Achats',
        'details' => 'Voir les détails',
        'quik'=> 'Aperçu rapide',
        'delete'=> 'Supprimer le compte',
        'edit' => 'Editer le profil',
        'update'=> 'mise à jour',
        'forgot'=> 'mot de passe oublié?',
        'view' => 'Voir plus',
        'type' => 'type',
        'text'=> 'Si vous envisagez un nouvel ordinateur portable, recherchez un nouvel autoradio puissant ou achetez un nouveau téléviseur HD, nous vous facilitons la tâche.
        trouvez exactement ce dont vous avez besoin à un prix abordable. Nous offrons des prix bas tous les jours sur les téléviseurs, ordinateurs portables, téléphones portables, tablettes
        et iPads, jeux vidéo, ordinateurs de bureau, appareils photo et caméscopes, audio, vidéo et plus encore.',
        'free'=> 'Livraison gratuite',
        'desfree'=>'sur les commandes de plus de 100 $',
        'fast'=> 'Livraison rapide',
        'desfast'=> 'À l\'échelle mondiale',
        'big' =>'Grand choix',
        'desbig'=> 'de produits',
        'qklink' => 'Liens rapides',
        'aboutt'=> 'À propos de nous',
        'contact' => 'Contact Us',
        'help' => 'Aidez-moi',
        'fa'=> 'FAQ',
        'term' => 'Conditions d\'utilisation',
        'priv' => 'Politique de confidentialité',
        'get' => 'Entrer en contact',
        'news' => 'Newsletter',
        'desnews'=>'Livraison gratuite sur votre première commande!',
        'follow'=> 'Suivez-nous sur',
        'payment'=>'Mode de paiement',
        'cash'=>'paiement à la livraison',
        'pr'=>'prix',
        'check'=>'Check-out',
        'add'=> 'Ajouter de nouveaux détails',
        'chst'=>'choisissez statu',
        'nw'=>'Nouveau',
        'lknw'=> 'comme neuf',
        'us'=>'utilisé',
        'vr'=>"très vieux",
        'productnm'=>'Nom du produit',
        'qn'=>'Quantité',
        'product'=> 'Produit',
        'mobile'=>'numéro de portable',
        'adress'=>'Adresse complète',
        'del'=> 'Livraison à cette adresse',
        'selpm'=> 'Sélectionnez le mode de paiement',
        'pm'=> 'Paiement',
        'post'=> 'Compte postal',
        'ppl'=>'Compte Paypal',
        'select'=> 'sélectionner',
        'info'=> 'information',
        'inv'=> 'la facture d\'impression',
        'plsinv'=> 'Veuillez payer pour cet instrument et envoyer le clip en cliquant sur le bouton ci-dessous',
        'send'=> 'envoyer',
        'comup'=> 'mettre à jour le commentaire',
        'dt'=>'date',
        'top' => ' Meilleures offres et réductions ',
        'can'=> 'Annuler',
        'chimg'=>'choisissez l\'image',
        'upload'=> 'upload',
        'en'=> 'anglais',
        'ar'=> 'arabe',
        'fr'=> 'français',
        'shop' => 'Achetez',
        'srhe'=> 'Cherche ici..',
        'prnm'=> 'Nom du produit ...',
        'contactus'=> 'contact',
        'call'=> 'telephone',
        'ms'=> 'message',
        'welcome'=> 'bonjour'


    );

    return $lang[$ph];

}

?>