<?php

function lang($ph)
{
    static $lang = array(
        'titleLog' => 'login',
        'dash' => 'dashboard',
        'cat' => 'Categories',
        'It' => 'Items',
        'mem' => 'Members',
        'stat' => 'Statistics',
        'log' => 'Logs',
        'ed' => 'edit profile',
        'set'=> 'settings',
        'out'=>'LogOut',
        'editmem'=> 'Edit memeber',
        'user' =>'username',
        'paswd'=>'password',
        'email' =>'email',
        'name' =>'full Name',
        'up' => 'update',
        'con' => 'check to confirm',
        'taken' => 'this password alredy taken',
        'taken1'=> 'this email alredy taken',
        'taken2'=> 'this name alredy taken',
        'taken3'=> 'this username alredy taken',
        'up1' => 'updated',
        'add' => 'add member',
        'addsuc' => 'you have adding new memeber',
        'manage' => 'Manage members',
        'edit' => 'Edit',
        'del' => 'Delete',
        'delrecor'=> ' you have deleted one user',
        'msg' => 'you will be redirect in 3 seconds',
        'updatemem'=> 'update member',
        'upsucc' => 'you have update succesfully',
        'total' => 'total members',
        'pending' => 'pending members',
        'totit' => 'total items',
        'totco'=> 'total comments',
        'lts' => 'latest  registred users ',
        'ltsi'=> 'latest registred items',
        'details' => 'View Details',
        'managepen'=> 'Manage pending members',
        'activate'=> 'activate',
        'view' => 'view more',
        'addcat'=> 'Add new category',
        'namecat'=> 'Name',
        'descc' => 'Description',
        'order' => 'ordering',
        'addca'=> 'Add category',
        'visible'=> 'visible',
        'com'=>'comments',
        'ads'=> 'Ads',
        'y'=> 'yes',
        'n' =>'no',
        'please'=> 'please enter the name description',
        'addcatsuc' => 'categorie added succefully',
        'mancat'=> 'Manage Categories',
        'delcat' => 'Categorie deleted succesfully',
        'upcat' => 'Update categorie',
        'avb'=> 'Sorry this content is not available',
        'upcatmessage' => 'categorie updated succesfully',
        'upcaterror' => 'please fill the informations',
        'asc' => 'ASC',
        'desc' => 'DESC',
        'vw'=>'view',
        'full'=> 'full',
        'classic'=>'classic',
        'pr'=>'price',
        'cntr'=>'Country',
        'chcntr'=>'choose country',
        'st'=> 'status',
        'chst'=>'choose statu',
        'nw'=>'new',
        'lknw'=> 'Like new',
        'us'=>'used',
        'vr'=>"very old",
        'memsin'=>'member',
        'addit'=>'Add item',
        'vaddit'=> 'you have adding new item',
        'addph'=> 'add photo',
        'delph'=> 'delete photo',
        'chphoto'=> 'Choose photo',
        'upload'=>'upload',
        'selphoto'=> 'please select a photo',
        'upitem'=> 'update item',
        'com'=> 'comments',
        'itdel'=> 'item deleted successfully',
        'itup'=> 'item updated successfully',
        'comup'=> 'update comment',
        'dt'=>'date',
        'lan' => 'language',
        'ar'=> 'arabic',
        'en' => 'english',
        'fr' => 'french',
        'users'=> 'users',
        'orders'=> 'orders',
        'pur'=> 'purchases',
        'appr'=> 'approve'


    );

    return $lang[$ph];

}

?>