<?php

function lang($ph)
{
    static $lang = array(
        'titleLog' => 's\'identifier',
        'dash' => 'tableau de bord',
        'cat' => 'Les catégories',
        'It' => 'produits',
        'mem' => 'Membres',
        'stat' => 'Statistiques',
        'log' => 'Le registre',
        'ed' => 'Editer le profil',
        'set'=> 'réglages',
        'out'=>'Se déconnecter',
        'editmem'=> 'Modifier le membre',
        'user' =>'Nom d\'utilisateur',
        'paswd'=>'mot de passe',
        'email' =>'email',
        'name' =>'nom complet',
        'up' => 'mise à jour',
        'con' => 'vérifier pour confirmer',
        'taken' => 'ce mot de passe déjà pris',
        'taken1'=> 'cet email déjà pris',
        'taken2'=> 'ce nom déjà pris',
        'taken3'=> 'ce nom d\'utilisateur déjà pris',
        'up1' => 'mise à jour',
        'add' => 'ajouter un membre',
        'addsuc' => 'vous avez ajouté un nouveau membre',
        'manage' => 'Gérer les membres',
        'edit' => 'Éditer',
        'del' => 'Supprimer',
        'delrecor'=> ' vous avez supprimé un utilisateur',
        'msg' => 'vous serez redirigé dans 3 secondes',
        'updatemem'=> 'mettre à jour le membre',
        'upsucc' => 'vous avez mis à jour avec succès',
        'total' => 'nombre total de membres',
        'pending' => 'membres en attente',
        'totit' => 'produit au total',
        'totco'=> 'total des commentaires',
        'lts' => 'derniers utilisateurs enregistrés ',
        'ltsi'=> 'derniers produit enregistrés',
        'details' => 'Voir les détails',
        'managepen'=> 'Gérer les membres en attente',
        'activate'=> 'Activer',
        'view' => 'Voir plus',
        'addcat'=> 'Ajouter une nouvelle catégorie',
        'namecat'=> 'Nom',
        'descc' => 'La description',
        'order' => 'ordonner',
        'addca'=> 'Ajouter une catégorie',
        'visible'=> 'visible',
        'com'=>'commentaires',
        'ads'=> 'Les publicités',
        'y'=> 'oui',
        'n' =>'non',
        'please'=> 'veuillez saisir la description du nom',
        'addcatsuc' => 'catégorie ajoutée avec succès',
        'mancat'=> 'Gérer les catégories',
        'delcat' => 'Catégorie supprimée avec succès',
        'upcat' => 'Mettre à jour la catégorie',
        'avb'=> 'Désolé, ce contenu n\'est pas disponible',
        'upcatmessage' => 'catégorie mise à jour avec succès',
        'upcaterror' => 'veuillez remplir les informations',
        'asc' => 'ascendant',
        'desc' => 'descente',
        'vw'=>'voir',
        'full'=> 'plein',
        'classic'=>'classique',
        'pr'=>'prix',
        'cntr'=>'Pays',
        'chcntr'=>'choisissez un pays',
        'st'=> 'statut',
        'chst'=>'choisissez statu',
        'nw'=>'Nouveau',
        'lknw'=> 'Comme neuf',
        'us'=>'utilisé',
        'vr'=>"très vieux",
        'memsin'=>'membre',
        'addit'=>'Ajouter un produit',
        'vaddit'=> 'vous avez ajouté un nouvel élément',
        'addph'=> 'ajouter une photo',
        'delph'=> 'supprimer la photo',
        'chphoto'=> 'Choisissez une photo',
        'upload'=>'télécharger',
        'selphoto'=> 'veuillez sélectionner une photo',
        'upitem'=> 'mettre à jour l\'élément',
        'com'=> 'commentaires',
        'itdel'=> 'élément supprimé avec succès',
        'itup'=> 'élément mis à jour avec succès',
        'comup'=> 'mettre à jour le commentaire',
        'dt'=>'date',
        'lan' => 'Langue',
        'ar'=> 'arabe',
        'en' => 'Anglais',
        'fr' => 'français',
        'users'=> 'client',
        'orders'=> 'demandes',
        'pur'=> 'payment',
        'appr'=> 'approve'


    );

    return $lang[$ph];

}

?>